### ISSUE TITLE
Can't use this package with Expo

### ISSUE THREAD

**Issue by EduardoRoc97** [Gustash/react-native-smart-lock#1]
Hello, I'm here with a problem: I'm trying to implement the SmartLock in my React Native app for Android and it gives me always error when I try to use the methods of the object to perform the actions of SmartLock in Android, because of the object "SmartLock" is null.
![image](https://user-images.githubusercontent.com/55397247/82880989-04287780-9f37-11ea-9668-d5f40a177de7.png)

I wanted you to take a look at your index.js file to see where it is going wrong.

**Comment by Gustash** [comment]
How are you importing it? Also, can you share the specific error you get?

**Comment by EduardoRoc97** [comment]
I'm developing my app in Expo and I followed the steps described in the README section, but I'm getting the following error: 
![image](https://user-images.githubusercontent.com/55397247/82893384-d1877a80-9f48-11ea-8e35-bfa01d681c30.png)
I'm importing the code in the following way.
![image](https://user-images.githubusercontent.com/55397247/82893470-f4b22a00-9f48-11ea-9eb0-c30f2653a6d4.png)
and I'm using it in the following way:
![image](https://user-images.githubusercontent.com/55397247/82893602-2a571300-9f49-11ea-9053-3e316750113f.png)
I've been exploring your index.js file and, makin console.log in SmartLock, is giving me null on that object:
![image](https://user-images.githubusercontent.com/55397247/82893718-596d8480-9f49-11ea-8c09-fcdb1ec57e8d.png)
Could you explain me why it's giving me this error?

**Comment by Gustash** [comment]
You can't use this package with Expo because you can't use native packages that are not packaged in by Expo. You might be able to use this if you eject to an ExpoKit project, but I personally haven't tried that. 

You're getting null because there is no SmartLock in your NativeModules, precisely for that reason.
