### ISSUE TITLE
Android 10 problems

### ISSUE THREAD

**Issue by daimonkor** [Gustash/react-native-smart-lock#2]
Please fix problem with autofill at Android 10 https://prnt.sc/tdmjdi

  save to google smart lock canceled16: Credentials API's save confirmation dialog has been disabled to avoid conflicts with the Android Autofill feature. This choice may be overridden via CredentialsOptions.

I enabled https://prnt.sc/tdmjnn 
 https://prnt.sc/tdmjx8

https://developers.google.com/identity/smartlock-passwords/android/store-credentials

Thanks for help

**Comment by Gustash** [comment]
I had this option enabled on a previous version, but removed it since the documentation suggests you don't force it to keep the UI consistent with other apps. 

This works on every project I've used it in, all the way until Android 10. 

Are you wrapping the calls in try..catch like the example project is? You get this API error, but smart lock still works since it brings up the native UI.

**Comment by daimonkor** [comment]
@Gustash  It i only logbox), release works without crash

**Comment by Gustash** [comment]
I assume you're doing a `console.error`. If you remove that, does it work?

**Comment by daimonkor** [comment]
So maybe fixed https://prnt.sc/tdmv6f

I change your file   CredentialsOptions options = new CredentialsOptions.Builder().forceEnableSaveDialog().build();

and  <InputRNE
        importantForAutofill="noExcludeDescendants" .....>

Please update library and description for Android 10, thanks a lot.

**Comment by daimonkor** [comment]
> I assume you're doing a `console.error`. If you remove that, does it work?

Problem was with Google API

**Comment by Gustash** [comment]
The error is disingenuous. It's not an actual error, it's more of a warning. It should function just fine if you ignore that

**Comment by Gustash** [comment]
I'm closing this "error" can just be ignored. I'm not adding `forceEnableSaveDialog` to this library because the documentation recommends you don't use it to keep the flow consistent between apps.
