### ISSUE TITLE
Getting canceled in Android 10

### ISSUE THREAD

**Issue by joaocosta9** [Gustash/react-native-smart-lock#3]
Hello! Does this package works with android 10? I'm getting "cancelled" when I try to save my credentials. It says in the documentation "The save method might be canceled if the system wants to give priority to the password manager UI instead". What is this password managet UI? Is there anyway I can turn this around?

Thank you

**Comment by fonov** [comment]
HI, i also discover this issue. i always get "cancelled" on android 10 run in emulator, but when i run on device with android 10 everything work fine. 

[From documentation](https://developers.google.com/identity/smartlock-passwords/android/store-credentials) "cancelled" mean 

> If the user chooses not to save credentials, the user won't be prompted again to save any account's credentials for the app. If you call CredentialsClient.save() after a user has opted out, its result will have a status code of CANCELED. The user can opt in later from the Google Settings app, in the Smart Lock for Passwords section. The user must enable credential saving for all accounts to be prompted to save credentials next time.

**Comment by joaocosta9** [comment]
Hi @fonov . Yes smart lock does not work for emulator (I believe its the normal behaviour). I later discovered from multiple sources that smart lock can have problems in some Android 10 devices, I tried in different android 10 smarthphones and it worked in some of them, and on others not. I also tried the package in other android versions and everything was working fine. I think the smartlock malfunction in android 10  has nothing to do with this package, since I also checked the native code, and evreything was according with the documentation.

**Comment by melvinchng** [comment]
I was facing the same issue of getting `Cancelled`. I realized that I have multiple Google account signed in on the device. One of the account had "Never" save password for the app. I removed the never save password for the Google account and it works flawlessly.
